import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    darkMode: 'class',
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
    ],

    theme: {
        extend: {
            fontFamily: {
                sans: ['IBM Plex Sans Arabic', ...defaultTheme.fontFamily.sans],
                headline: ['Montserrat', 'Public Sans', 'sans-serif'],
                body: ['Inter', 'Public Sans', 'sans-serif'],
                display: ['Montserrat', 'sans-serif'],
                label: ['Inter', 'sans-serif'],
                'body-lg': ['Inter'],
                'body-md': ['Inter'],
                'body-sm': ['Inter'],
                'headline-xl': ['Inter'],
                'headline-lg': ['Inter'],
                'headline-md': ['Inter'],
                'label-md': ['Inter'],
            },
            fontSize: {
                'body-lg': ['18px', { lineHeight: '28px', fontWeight: '500' }],
                'headline-md': ['24px', { lineHeight: '30px', fontWeight: '600' }],
                'body-md': ['16px', { lineHeight: '24px', fontWeight: '500' }],
                'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
                'headline-xl': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
                'headline-lg': ['32px', { lineHeight: '38px', letterSpacing: '-0.01em', fontWeight: '700' }],
                'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
            },
            spacing: {
                'page-padding': '32px',
                'page-padding-h': '40px',
                'page-padding-v': '60px',
                'section-margin': '48px',
                'component-gap': '24px',
                'grid-gap': '24px',
                'tight-gap': '8px',
                'card-padding': '20px',
                'element-gap': '16px',
            },
            colors: {
                'welcome-primary': '#050A30',
                'welcome-secondary': '#2932FF',
                'welcome-tertiary': '#7EC8E3',
                'welcome-surface': '#FFFFFF',
                'welcome-on-surface': '#050A30',
                'welcome-on-surface-variant': '#4A4A4A',
                'welcome-outline-variant': '#E0E0E0',
                navy: {
                    950: '#0E1122',
                    900: '#131633',
                    800: '#181B40',
                    700: '#1E2150',
                    600: '#26295C',
                    500: '#30336A',
                },
                primary: {
                    DEFAULT: '#4D5079',
                    light: '#6B6E98',
                    bright: '#8A8DB8',
                    dark: '#2D304A',
                    vivid: '#250AA3',
                },
                accent: {
                    purple: '#6D52E0',
                    deep: '#4A30C0',
                    rich: '#8C72F0',
                    vivid: '#250AA3',
                },
                gold: {
                    DEFAULT: '#C9A96E',
                    light: '#D8C18E',
                    dark: '#A8894E',
                },
                teal: {
                    DEFAULT: '#1E8A6E',
                    light: '#2AAA84',
                    dark: '#166A54',
                },
                coral: {
                    DEFAULT: '#D45A6A',
                    light: '#E87888',
                    dark: '#B04050',
                },
                ice: {
                    DEFAULT: '#4A8BB7',
                    light: '#6AA8D0',
                    dark: '#3A6A90',
                },
                rose: {
                    DEFAULT: '#D05A8A',
                    light: '#E078A8',
                    dark: '#B04070',
                },
                sand: {
                    DEFAULT: '#B8A08A',
                    light: '#D0BEA8',
                    dark: '#887868',
                },
                surface: {
                    DEFAULT: '#181B40',
                    light: '#6B6E98',
                    card: '#181B40',
                    hover: '#6B6E98',
                    border: '#181B40',
                },
                text: {
                    primary: '#EEEDF5',
                    secondary: '#A8A6C0',
                    muted: '#787690',
                },
                // Stitch Material Design 3 colors (non-conflicting flat keys)
                'on-surface': '#e3e1f0',
                'on-surface-variant': '#c5c4da',
                'surface-dim': '#12131d',
                'surface-bright': '#383844',
                'surface-container-lowest': '#0d0d17',
                'surface-container-low': '#1a1b25',
                'surface-container': '#1e1f2a',
                'surface-container-high': '#292934',
                'surface-container-highest': '#34343f',
                'surface-variant': '#34343f',
                'surface-tint': '#bec2ff',
                'on-background': '#e3e1f0',
                'background': '#12131d',
                'error': '#ffb4ab',
                'on-error': '#690005',
                'error-container': '#93000a',
                'on-error-container': '#ffdad6',
                'inverse-surface': '#e3e1f0',
                'inverse-on-surface': '#2f2f3b',
                'inverse-primary': '#333dff',
                'outline': '#8f8fa3',
                'outline-variant': '#454557',
                'on-primary': '#0002ab',
                'on-primary-container': '#caccff',
                'primary-container': '#2932ff',
                'secondary': '#c9bfff',
                'on-secondary': '#2e009c',
                'secondary-container': '#4720ca',
                'on-secondary-container': '#baaeff',
                'tertiary': '#ffb4a4',
                'on-tertiary': '#630e00',
                'tertiary-container': '#ad2000',
                'on-tertiary-container': '#ffc1b4',
                'gold-accent': '#D4AF37',
                'teal-accent': '#2DD4BF',
                'trips-primary': '#3B82F6',
                'trips-primary-hover': '#2563EB',
                'trips-gold': '#FACC15',
                'trips-purple': '#8B5CF6',
                'trips-bg': '#6366F1',
                'dark-bg': '#0D0F1A',
                'light-bg': '#FFFFFF',
                'dark-surface': 'rgba(255, 255, 255, 0.06)',
                'light-surface': '#F7F7F7',
                'dark-border': 'rgba(255, 255, 255, 0.12)',
                'light-border': 'rgba(0, 0, 0, 0.08)',
                'primary-fixed': '#e0e0ff',
                'primary-fixed-dim': '#bec2ff',
                'on-primary-fixed': '#00016d',
                'on-primary-fixed-variant': '#0002ee',
                'secondary-fixed': '#e5deff',
                'secondary-fixed-dim': '#c9bfff',
                'on-secondary-fixed': '#1a0063',
                'on-secondary-fixed-variant': '#441cc8',
                'tertiary-fixed': '#ffdad3',
                'tertiary-fixed-dim': '#ffb4a4',
                'on-tertiary-fixed': '#3d0600',
                'on-tertiary-fixed-variant': '#8c1800',
            },
            borderRadius: {
                'xs': '6px',
                'sm': '8px',
                'DEFAULT': '12px',
                'md': '14px',
                'lg': '16px',
                'xl': '20px',
                '2xl': '24px',
                'pill': '9999px',
            },
            boxShadow: {
                'soft': '0 2px 16px rgba(0, 0, 0, 0.5)',
                'card': '0 4px 24px rgba(0, 0, 0, 0.5)',
                'card-hover': '0 8px 40px rgba(0, 0, 0, 0.6), 0 0 0 1px rgba(77, 80, 121, 0.15)',
                'elevated': '0 20px 60px rgba(0, 0, 0, 0.7)',
                'glow-primary': '0 0 20px rgba(77, 80, 121, 0.25)',
                'glow-purple': '0 0 20px rgba(109, 82, 224, 0.25)',
                'glow-gold': '0 0 20px rgba(201, 169, 110, 0.25)',
                'glow-coral': '0 0 20px rgba(212, 90, 106, 0.25)',
                'glow-ice': '0 0 20px rgba(74, 139, 183, 0.25)',
            },
            backgroundImage: {
                'gradient-radial': 'radial-gradient(ellipse at center, var(--tw-gradient-stops))',
                'hero-glow': 'radial-gradient(ellipse at 50% 0%, rgba(109, 82, 224, 0.05) 0%, transparent 60%)',
                'btn-primary': 'linear-gradient(135deg, #4D5079 0%, #6B6E98 100%)',
                'btn-primary-hover': 'linear-gradient(135deg, #5D6089 0%, #7B7EA8 100%)',
                'btn-accent': 'linear-gradient(135deg, #6D52E0 0%, #8C72F0 100%)',
                'btn-gold': 'linear-gradient(135deg, #C9A96E 0%, #D8C18E 100%)',
                'btn-coral': 'linear-gradient(135deg, #D45A6A 0%, #E87888 100%)',
                'btn-ice': 'linear-gradient(135deg, #4A8BB7 0%, #6AA8D0 100%)',
            },
            keyframes: {
                'fade-in': {
                    '0%': { opacity: '0', transform: 'translateY(12px)' },
                    '100%': { opacity: '1', transform: 'translateY(0)' },
                },
                'fade-in-up': {
                    '0%': { opacity: '0', transform: 'translateY(24px)' },
                    '100%': { opacity: '1', transform: 'translateY(0)' },
                },
                'scale-in': {
                    '0%': { opacity: '0', transform: 'scale(0.96)' },
                    '100%': { opacity: '1', transform: 'scale(1)' },
                },
                'slide-up': {
                    '0%': { opacity: '0', transform: 'translateY(20px)' },
                    '100%': { opacity: '1', transform: 'translateY(0)' },
                },
                'slide-down': {
                    '0%': { opacity: '0', transform: 'translateY(-8px)' },
                    '100%': { opacity: '1', transform: 'translateY(0)' },
                },
                'pulse-soft': {
                    '0%, 100%': { opacity: '1' },
                    '50%': { opacity: '0.6' },
                },
            },
            animation: {
                'fade-in': 'fade-in 0.5s cubic-bezier(0.16, 1, 0.3, 1)',
                'fade-in-up': 'fade-in-up 0.6s cubic-bezier(0.16, 1, 0.3, 1)',
                'scale-in': 'scale-in 0.4s cubic-bezier(0.16, 1, 0.3, 1)',
                'slide-up': 'slide-up 0.5s cubic-bezier(0.16, 1, 0.3, 1)',
                'slide-down': 'slide-down 0.3s cubic-bezier(0.16, 1, 0.3, 1)',
                'pulse-soft': 'pulse-soft 2s ease-in-out infinite',
            },
        },
    },

    plugins: [forms],
};
